//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManifestServiceClient.ManifestServiceClientReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManifestServiceClientReference.IPackageManifestService")]
    public interface IPackageManifestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageManifestService/Ping", ReplyAction="http://tempuri.org/IPackageManifestService/PingResponse")]
        bool Ping(ref string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageManifestService/ManifestsConfirmed", ReplyAction="http://tempuri.org/IPackageManifestService/ManifestsConfirmedResponse")]
        System.Collections.Generic.List<DocumentScannerCommon.PackageManifest> ManifestsConfirmed(DocumentScannerServiceCommon.ManifestContract contract, ref string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageManifestService/DocumentsConfirmed", ReplyAction="http://tempuri.org/IPackageManifestService/DocumentsConfirmedResponse")]
        System.Collections.Generic.List<DocumentScannerCommon.ImageFile> DocumentsConfirmed(DocumentScannerServiceCommon.ManifestContract contract, ref string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageManifestService/ManifestsAvailable", ReplyAction="http://tempuri.org/IPackageManifestService/ManifestsAvailableResponse")]
        System.Collections.Generic.List<DocumentScannerCommon.PackageManifest> ManifestsAvailable(DocumentScannerServiceCommon.ManifestContract contract, ref string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPackageManifestService/DocumentsAvailable", ReplyAction="http://tempuri.org/IPackageManifestService/DocumentsAvailableResponse")]
        System.Collections.Generic.List<DocumentScannerCommon.ImageFile> DocumentsAvailable(DocumentScannerServiceCommon.ManifestContract contract, ref string errorMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPackageManifestServiceChannel : ManifestServiceClient.ManifestServiceClientReference.IPackageManifestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PackageManifestServiceClient : System.ServiceModel.ClientBase<ManifestServiceClient.ManifestServiceClientReference.IPackageManifestService>, ManifestServiceClient.ManifestServiceClientReference.IPackageManifestService {
        
        public PackageManifestServiceClient() {
        }
        
        public PackageManifestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PackageManifestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackageManifestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackageManifestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping(ref string errorMessage) {
            return base.Channel.Ping(ref errorMessage);
        }
        
        public System.Collections.Generic.List<DocumentScannerCommon.PackageManifest> ManifestsConfirmed(DocumentScannerServiceCommon.ManifestContract contract, ref string errorMessage) {
            return base.Channel.ManifestsConfirmed(contract, ref errorMessage);
        }
        
        public System.Collections.Generic.List<DocumentScannerCommon.ImageFile> DocumentsConfirmed(DocumentScannerServiceCommon.ManifestContract contract, ref string errorMessage) {
            return base.Channel.DocumentsConfirmed(contract, ref errorMessage);
        }
        
        public System.Collections.Generic.List<DocumentScannerCommon.PackageManifest> ManifestsAvailable(DocumentScannerServiceCommon.ManifestContract contract, ref string errorMessage) {
            return base.Channel.ManifestsAvailable(contract, ref errorMessage);
        }
        
        public System.Collections.Generic.List<DocumentScannerCommon.ImageFile> DocumentsAvailable(DocumentScannerServiceCommon.ManifestContract contract, ref string errorMessage) {
            return base.Channel.DocumentsAvailable(contract, ref errorMessage);
        }
    }
}
