//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferServiceClient.TransferServiceClientReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransferServiceClientReference.IFileTransferService")]
    public interface IFileTransferService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransferService/Ping", ReplyAction="http://tempuri.org/IFileTransferService/PingResponse")]
        bool Ping(ref string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransferService/Push", ReplyAction="http://tempuri.org/IFileTransferService/PushResponse")]
        bool Push(DocumentScannerServiceCommon.TransferContract transferContract, ref string errorMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransferService/Pull", ReplyAction="http://tempuri.org/IFileTransferService/PullResponse")]
        bool Pull(ref DocumentScannerServiceCommon.TransferContract transferContract, ref string errorMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileTransferServiceChannel : TransferServiceClient.TransferServiceClientReference.IFileTransferService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileTransferServiceClient : System.ServiceModel.ClientBase<TransferServiceClient.TransferServiceClientReference.IFileTransferService>, TransferServiceClient.TransferServiceClientReference.IFileTransferService {
        
        public FileTransferServiceClient() {
        }
        
        public FileTransferServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileTransferServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping(ref string errorMessage) {
            return base.Channel.Ping(ref errorMessage);
        }
        
        public bool Push(DocumentScannerServiceCommon.TransferContract transferContract, ref string errorMessage) {
            return base.Channel.Push(transferContract, ref errorMessage);
        }
        
        public bool Pull(ref DocumentScannerServiceCommon.TransferContract transferContract, ref string errorMessage) {
            return base.Channel.Pull(ref transferContract, ref errorMessage);
        }
    }
}
